# SciKit-Learn

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100, (10,2))

In [4]:
data

array([[35, 76],
       [30, 50],
       [44, 55],
       [85, 77],
       [97, 13],
       [45, 12],
       [62, 47],
       [68, 23],
       [42, 73],
       [35, 18]])

In [5]:
scalar_model = MinMaxScaler()

In [6]:
scalar_model.fit(data)

C:\Users\eslem\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
data

array([[35, 76],
       [30, 50],
       [44, 55],
       [85, 77],
       [97, 13],
       [45, 12],
       [62, 47],
       [68, 23],
       [42, 73],
       [35, 18]])

In [8]:
scalar_model.transform(data)

array([[ 0.07462687,  0.98461538],
       [ 0.        ,  0.58461538],
       [ 0.20895522,  0.66153846],
       [ 0.82089552,  1.        ],
       [ 1.        ,  0.01538462],
       [ 0.2238806 ,  0.        ],
       [ 0.47761194,  0.53846154],
       [ 0.56716418,  0.16923077],
       [ 0.17910448,  0.93846154],
       [ 0.07462687,  0.09230769]])

In [9]:
scalar_model.fit_transform(data)

C:\Users\eslem\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.07462687,  0.98461538],
       [ 0.        ,  0.58461538],
       [ 0.20895522,  0.66153846],
       [ 0.82089552,  1.        ],
       [ 1.        ,  0.01538462],
       [ 0.2238806 ,  0.        ],
       [ 0.47761194,  0.53846154],
       [ 0.56716418,  0.16923077],
       [ 0.17910448,  0.93846154],
       [ 0.07462687,  0.09230769]])

In [10]:
import pandas as pd

In [20]:
df  = pd.DataFrame(data = np.random.randint(0,101, (50,4)), columns = ['f1','f2','f3', 'label'])

In [21]:
df

f1  f2  f3  label
0   80  92  16     17
1    1  46  33     43
2   44  27  44     39
3   18  41  76     86
4   41  83  34     76
5   23  75  49      9
6   85  35  13     84
7   83  73  65     78
8   59  81   2     14
9   86  88  93     92
10  53   9  63     90
11  83  94  60     32
12  68  11  74     35
13  33  18  64      7
14  27  16  47     75
15  38  30  75     26
16   2  43  95     12
17  17  56  15     94
18  23   4  35    100
19  64  72  76      3
20  67  76  86     35
21  38   8   9     96
22  11  75  67     24
23  14  41  66     37
24  49  70  99     40
25  39   6   1     78
26  95  13  97     22
27  16  88  65     85
28  90  20  61     51
29  24  60  65     56
30   2  98  55     46
31  76  49  32     16
32  34  86  59     92
33  50  88  64     92
34  27  87  19     12
35  12  23  64      7
36  26  41  36      5
37  98  45   7     13
38  76   4  90     47
39  62  51  95     30
40  79  37  10     88
41  29  78  40     57
42  88  34  56     76
43   5  47  17     63
44  54  75  10     42
45  68  99   3      6
46  12  65   7     34
47  35  78   7      8
48  78  99  44     71
49  26   2  62     56

In [22]:
x = df[['f1','f2','f3']]

In [23]:
y = df[['label']]

In [24]:
y

label
0      17
1      43
2      39
3      86
4      76
5       9
6      84
7      78
8      14
9      92
10     90
11     32
12     35
13      7
14     75
15     26
16     12
17     94
18    100
19      3
20     35
21     96
22     24
23     37
24     40
25     78
26     22
27     85
28     51
29     56
30     46
31     16
32     92
33     92
34     12
35      7
36      5
37     13
38     47
39     30
40     88
41     57
42     76
43     63
44     42
45      6
46     34
47      8
48     71
49     56

In [25]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state = 101)

In [30]:
X_train.shape

(35, 3)

In [34]:
X_test.shape

(15, 3)